<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ECSGame.Module.ResourceData</RootNamespace>
    <Nullable>enable</Nullable>
	  <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
	  <Compile Include=".\**\*.cs" />
	  <Compile Remove=".\obj\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EcsNode" Version="1.0.1" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

</Project>
