<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<RootNamespace>ECSGame.Module.Building</RootNamespace>
		<Nullable>enable</Nullable>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include=".\**\*.cs" />
		<Compile Remove=".\obj\**\*.cs" />
		<Compile Remove=".\system.module-test.neter\**\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="com.model.neter\**\*.cs" />
		<Compile Include="com.system.neter\**\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EcsNode" Version="1.0.2" />
		<PackageReference Include="MessagePack" Version="3.1.4" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
	</ItemGroup>

</Project>
