
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.data
{
public sealed partial class GridPlaneConfig : Luban.BeanBase
{
    public GridPlaneConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["width"].IsNumber) { throw new SerializationException(); }  Width = _buf["width"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
        { if(!_buf["cell_size"].IsNumber) { throw new SerializationException(); }  CellSize = _buf["cell_size"]; }
    }

    public static GridPlaneConfig DeserializeGridPlaneConfig(JSONNode _buf)
    {
        return new data.GridPlaneConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 网格区域宽度
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 网格区域高度
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 单个格子的大小
    /// </summary>
    public readonly float CellSize;
   
    public const int __ID__ = -1479443660;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "cellSize:" + CellSize + ","
        + "}";
    }
}
}

