
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.data
{ 
    public enum GridCellState
    {
        /// <summary>
        /// 空置
        /// </summary>
        Empty = 0,
        /// <summary>
        /// 占用
        /// </summary>
        Occupied = 1,
    }

} 

