
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.data
{
public partial class TbGridPlane
{
    private readonly System.Collections.Generic.Dictionary<int, data.GridPlaneConfig> _dataMap;
    private readonly System.Collections.Generic.List<data.GridPlaneConfig> _dataList;
    
    public TbGridPlane(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, data.GridPlaneConfig>(count);
        _dataList = new System.Collections.Generic.List<data.GridPlaneConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            data.GridPlaneConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.data.GridPlaneConfig.DeserializeGridPlaneConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, data.GridPlaneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<data.GridPlaneConfig> DataList => _dataList;

    public data.GridPlaneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public data.GridPlaneConfig Get(int key) => _dataMap[key];
    public data.GridPlaneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

