
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.data
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, data.ItemConfig> _dataMap;
    private readonly System.Collections.Generic.List<data.ItemConfig> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, data.ItemConfig>(count);
        _dataList = new System.Collections.Generic.List<data.ItemConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            data.ItemConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.data.ItemConfig.DeserializeItemConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, data.ItemConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<data.ItemConfig> DataList => _dataList;

    public data.ItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public data.ItemConfig Get(int key) => _dataMap[key];
    public data.ItemConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

