<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Code.Core\EcsNode\**\*.cs">
			<Link>EcsNode\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
		<Compile Include="..\Scripts\Sample\Model\**\*.cs">
			<Link>Model\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
		<Compile Include="..\Scripts\Sample\System\**\*.cs">
			<Link>System\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

</Project>
