
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public data.TbItem TbItem {get; }
    public demo.Tbitem Tbitem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new data.TbItem(loader("data_tbitem"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        Tbitem.ResolveRef(this);
    }
}

}
